apiVersion: apps/v1
kind: Deployment
metadata: 
  naame: nginx
  labels:
    app: web-app
spec: 
  replicas: 2
  selector:
    matchLabels:
     app: web-app
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: nginx_container
          image: nginx:latest
          ports:
            - containerPort: 80
          resources: 
            limits:
              memory: "200Mi"
              cpu: "200m"
            requests:
              memory: "200Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
            readinessProbe:
              httpGet:
                path: /
                port: 80
              initialDelaySeconds: 5
              periodSeconds: 10
      volumes: 
        - name: data
          persistantVolumeClaim:
            claimName: my-pvc