apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx_webserver
  labels: 
    app: nginx

spec:
  replicas: 2
  selector:
    matchlabels:
      app: nginx
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
    spec: 
      containers:
        - name: nginx_webserver
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 200Mi
          env: 
            - name: DATABASE_HOST
              value: db.example.com
            - name: API_Key
              valueFrom: 
                secretKeyRef:
                  name: my-secret
                  key: api-key
