apiVersion: v1
kind: Pod 
metadata:
  name: Purple
spec: 
  containers:
    - command:
        - sh
        - -c
        - echo app is running! && sleep 300
      image: busybox:1.28
      name: purle-container

  initContainers: 
    - name: warm-up-1
      image: busybox:1.28
      command:
        - sh
        - -c
        - sleep
    
    - name: warm-up-2
      image: busybox:1.28
      command: ["sh", "-c", "sleep 120"]

