apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod

spec:
  containers:
    - name: pod1
      image: nginx:latest
      ports:
        - containerPort: 80
    
    - name: pod2
      image: httpd
      ports:
        - containerPort: 8080